version: '3.4'
services:
  AC1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AC1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AC1_CloseCondition
      SET_PARAMS: AC1_CloseCondition
  AC5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AC5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AC5_CloseCondition
      SET_PARAMS: AC5_CloseCondition
  AC15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AC15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AC15_CloseCondition
      SET_PARAMS: AC15_CloseCondition
  AC30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AC30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AC30_CloseCondition
      SET_PARAMS: AC30_CloseCondition
