version: '3.4'
services:
  MFI1_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI1_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-MFI1_OpenCondition1
      SET_PARAMS: MFI1_OpenCondition1
      RUN_ON_SUCCESS: input_copy MFI1_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI5_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI5_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-MFI5_OpenCondition1
      SET_PARAMS: MFI5_OpenCondition1
      RUN_ON_SUCCESS: input_copy MFI5_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI15_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI15_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-MFI15_OpenCondition1
      SET_PARAMS: MFI15_OpenCondition1
      RUN_ON_SUCCESS: input_copy MFI15_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI30_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI30_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-MFI30_OpenCondition1
      SET_PARAMS: MFI30_OpenCondition1
      RUN_ON_SUCCESS: input_copy MFI30_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI1_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI1_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-MFI1_OpenCondition2
      SET_PARAMS: MFI1_OpenCondition2
      RUN_ON_SUCCESS: input_copy MFI1_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI5_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI5_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-MFI5_OpenCondition2
      SET_PARAMS: MFI5_OpenCondition2
      RUN_ON_SUCCESS: input_copy MFI5_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI15_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI15_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-MFI15_OpenCondition2
      SET_PARAMS: MFI15_OpenCondition2
      RUN_ON_SUCCESS: input_copy MFI15_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  MFI30_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-MFI30_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-MFI30_OpenCondition2
      SET_PARAMS: MFI30_OpenCondition2
      RUN_ON_SUCCESS: input_copy MFI30_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
