---
version: '3.4'
services:
  MACD1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-MACD1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD1_CloseCondition
      SET_PARAMS: MACD1_CloseCondition
  MACD5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-MACD5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD5_CloseCondition
      SET_PARAMS: MACD5_CloseCondition
  MACD15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-MACD15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD15_CloseCondition
      SET_PARAMS: MACD15_CloseCondition
  MACD30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-MACD30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-MACD30_CloseCondition
      SET_PARAMS: MACD30_CloseCondition
