version: '3.4'
services:
  AD1_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD1_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-AD1_OpenCondition1
      SET_PARAMS: AD1_OpenCondition1
      RUN_ON_SUCCESS: input_copy AD1_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD5_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD5_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-AD5_OpenCondition1
      SET_PARAMS: AD5_OpenCondition1
      RUN_ON_SUCCESS: input_copy AD5_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD15_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD15_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-AD15_OpenCondition1
      SET_PARAMS: AD15_OpenCondition1
      RUN_ON_SUCCESS: input_copy AD15_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD30_OpenCondition1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD30_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-AD30_OpenCondition1
      SET_PARAMS: AD30_OpenCondition1
      RUN_ON_SUCCESS: input_copy AD30_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD1_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD1_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-AD1_OpenCondition2
      SET_PARAMS: AD1_OpenCondition2
      RUN_ON_SUCCESS: input_copy AD1_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD5_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD5_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-AD5_OpenCondition2
      SET_PARAMS: AD5_OpenCondition2
      RUN_ON_SUCCESS: input_copy AD5_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD15_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD15_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-AD15_OpenCondition2
      SET_PARAMS: AD15_OpenCondition2
      RUN_ON_SUCCESS: input_copy AD15_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  AD30_OpenCondition2:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-AD30_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-AD30_OpenCondition2
      SET_PARAMS: AD30_OpenCondition2
      RUN_ON_SUCCESS: input_copy AD30_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
