---
version: '3.4'
services:
  Fractals1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-Fractals1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals1_CloseCondition
      SET_PARAMS: Fractals1_CloseCondition
  Fractals5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-Fractals5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals5_CloseCondition
      SET_PARAMS: Fractals5_CloseCondition
  Fractals15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-Fractals15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals15_CloseCondition
      SET_PARAMS: Fractals15_CloseCondition
  Fractals30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-Fractals30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Fractals30_CloseCondition
      SET_PARAMS: Fractals30_CloseCondition
