---
version: '3.4'
services:
  MinPipChangeToTrade:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 0.1 * 2"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 0.1 * 2")
        0.1
      SETFILE: /opt/sets/EA31337-MinPipChangeToTrade.set
      SET_PARAMS: MinPipChangeToTrade
      TEST_REPORT_NAME: EA31337-MinPipChangeToTrade
