version: '3.4'
services:
  AD1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EA31337-AD1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AD1_CloseCondition
      SET_PARAMS: AD1_CloseCondition
  AD5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EA31337-AD5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AD5_CloseCondition
      SET_PARAMS: AD5_CloseCondition
  AD15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EA31337-AD15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AD15_CloseCondition
      SET_PARAMS: AD15_CloseCondition
  AD30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-2
      SETFILE: /opt/sets/EA31337-AD30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-AD30_CloseCondition
      SET_PARAMS: AD30_CloseCondition
