---
version: '3.4'
services:
  Alligator1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Alligator1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Alligator1_CloseCondition
      SET_PARAMS: Alligator1_CloseCondition
  Alligator5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Alligator5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Alligator5_CloseCondition
      SET_PARAMS: Alligator5_CloseCondition
  Alligator15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Alligator15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Alligator15_CloseCondition
      SET_PARAMS: Alligator15_CloseCondition
  Alligator30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Alligator30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Alligator30_CloseCondition
      SET_PARAMS: Alligator30_CloseCondition
