version: '3.4'
services:
  EURUSD_ProfitFactorMinToTrade:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=80
      SET_PARAMS: ProfitFactorMinToTrade
      RUN_ON_SET: set_opt_params ProfitFactorMinToTrade $$(bc <<< "$$(input_get ProfitFactorMinToTrade) - 0.1 * 4") $$(bc <<< "$$(input_get ProfitFactorMinToTrade) + 0.1 * 4") 0.1
      SETFILE: /opt/sets/EA31337-ProfitFactorMinToTrade.set
      TEST_REPORT_NAME: EA31337-ProfitFactorMinToTrade
  EURUSD_StopLossMax:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SET_PARAMS: StopLossMax
      RUN_ON_SET: set_opt_params StopLossMax $$(bc <<< "$$(input_get StopLossMax) - 20 * 2") $$(bc <<< "$$(input_get StopLossMax) + 20 * 2") 20
      SETFILE: /opt/sets/EA31337-StopLossMax.set
      TEST_REPORT_NAME: EA31337-StopLossMax
  EURUSD_TakeProfitMax:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SET_PARAMS: TakeProfitMax
      RUN_ON_SET: set_opt_params TakeProfitMax $$(bc <<< "$$(input_get TakeProfitMax) - 20 * 2") $$(bc <<< "$$(input_get TakeProfitMax) + 20 * 2") 20
      SETFILE: /opt/sets/EA31337-TakeProfitMax.set
      TEST_REPORT_NAME: EA31337-TakeProfitMax
  EURUSD_TrailingProfit:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SET_PARAMS: TrailingProfit
      RUN_ON_SET: set_opt_params TrailingProfit $$(bc <<< "$$(input_get TrailingProfit) - 10 * 2") $$(bc <<< "$$(input_get TrailingProfit) + 10 * 2") 10
      SETFILE: /opt/sets/EA31337-TrailingProfit.set
      TEST_REPORT_NAME: EA31337-TrailingProfit
  EURUSD_TrailingStop:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SET_PARAMS: TrailingStop
      RUN_ON_SET: set_opt_params TrailingStop $$(bc <<< "$$(input_get TrailingStop) - 10 * 2") $$(bc <<< "$$(input_get TrailingStop) + 10 * 2") 10
      SETFILE: /opt/sets/EA31337-TrailingStop.set
      TEST_REPORT_NAME: EA31337-TrailingStop
  EURUSD_TrailingStopAddPerMinute:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=80
      SET_PARAMS: TrailingStopAddPerMinute
      RUN_ON_SET: set_opt_params TrailingStopAddPerMinute $$(bc <<< "$$(input_get TrailingStopAddPerMinute) - 0.1 * 2") $$(bc <<< "$$(input_get TrailingStopAddPerMinute) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EA31337-TrailingStopAddPerMinute.set
      TEST_REPORT_NAME: EA31337-TrailingStopAddPerMinute
# EURUSD_TrendPeriod:
#   command: run_backtest -v
#   image: ea31337/ea-tester:EURUSD-2018-DS
#   volumes:
#   - ./sets/EURUSD:/opt/sets:rw
#   - ./_results/EURUSD:/opt/_results:rw
#   env_file: ../EA-Tester.ini
#   environment:
#     EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
#     SET_PARAMS: TrendPeriod
#     RUN_ON_SET: set_opt_params TrendPeriod 5 1440 0
#     SETFILE: /opt/sets/EA31337-TrendPeriod.set
#     TEST_REPORT_NAME: EA31337-TrendPeriod
#     SET_PARAMS: TrendPeriod
