---
version: '3.4'
services:
  DeMarker1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-DeMarker1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker1_CloseCondition
      SET_PARAMS: DeMarker1_CloseCondition
  DeMarker5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-DeMarker5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker5_CloseCondition
      SET_PARAMS: DeMarker5_CloseCondition
  DeMarker15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-DeMarker15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker15_CloseCondition
      SET_PARAMS: DeMarker15_CloseCondition
  DeMarker30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-DeMarker30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-DeMarker30_CloseCondition
      SET_PARAMS: DeMarker30_CloseCondition
