---
version: '3.4'
services:
  SmartQueueActive:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      RUN_ON_SET: set_opt_params SmartQueueActive 0 1
      SETFILE: /opt/sets/EA31337-SmartQueueActive.set
      SET_PARAMS: SmartQueueActive
      TEST_REPORT_NAME: EA31337-SmartQueueActive
  SmartQueueMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      BT_MONTHS: 1-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      RUN_ON_SET: set_opt_params SmartQueueMethod 0 15
      SETFILE: /opt/sets/EA31337-SmartQueueMethod.set
      SET_PARAMS: SmartQueueMethod
      TEST_REPORT_NAME: EA31337-SmartQueueMethod
  SmartQueueFilter:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      BT_MONTHS: 1-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=1
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 5 * 10"))
        $$(get_min 255 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 5 * 10"))
        3
      SETFILE: /opt/sets/EA31337-SmartQueueFilter.set
      SET_PARAMS: SmartQueueFilter
      TEST_REPORT_NAME: EA31337-SmartQueueFilter
