---
version: '3.4'
services:
  Bands1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Bands1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands1_CloseCondition
      SET_PARAMS: Bands1_CloseCondition
  Bands5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Bands5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands5_CloseCondition
      SET_PARAMS: Bands5_CloseCondition
  Bands15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Bands15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands15_CloseCondition
      SET_PARAMS: Bands15_CloseCondition
  Bands30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Bands30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-Bands30_CloseCondition
      SET_PARAMS: Bands30_CloseCondition
