---
version: '3.4'
services:
  WPR1_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-WPR1_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR1_CloseCondition
      SET_PARAMS: WPR1_CloseCondition
  WPR5_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-WPR5_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR5_CloseCondition
      SET_PARAMS: WPR5_CloseCondition
  WPR15_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-WPR15_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR15_CloseCondition
      SET_PARAMS: WPR15_CloseCondition
  WPR30_CloseCondition:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-WPR30_CloseCondition.set
      TEST_REPORT_NAME: EA31337-WPR30_CloseCondition
      SET_PARAMS: WPR30_CloseCondition
