# yamllint disable rule:line-length
---
name: Lint YAML

on:
  pull_request:
    paths:
      - '*.y?ml'
  push:
    paths:
      - '*.y?ml'

jobs:
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
