# yamllint disable rule:line-length
---
name: Lint

on:
  pull_request:
    paths:
      - '*.md'
      - '*.y?ml'
      - '.github/workflows/lint.yml'
  push:
    paths:
      - '*.md'
      - '*.y?ml'
      - '.github/workflows/lint.yml'

jobs:
  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: .
          config_file: ".markdownlint.yaml"
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
