---
name: Optimize Strategy DeMarker

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-demarker'
      - 'optimize-strategy-demarker-*'

jobs:
  Optimize-CloseCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/DeMarker/CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA DeMarker1_CloseCondition
      - run: docker-compose run $DCA DeMarker5_CloseCondition
      - run: docker-compose run $DCA DeMarker15_CloseCondition
      - run: docker-compose run $DCA DeMarker30_CloseCondition
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-OpenCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/DeMarker/OpenCondition
    needs: Optimize-CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA DeMarker1_OpenCondition1
      - run: docker-compose run $DCA DeMarker5_OpenCondition1
      - run: docker-compose run $DCA DeMarker15_OpenCondition1
      - run: docker-compose run $DCA DeMarker30_OpenCondition1
      - run: docker-compose run $DCA DeMarker1_OpenCondition2
      - run: docker-compose run $DCA DeMarker5_OpenCondition2
      - run: docker-compose run $DCA DeMarker15_OpenCondition2
      - run: docker-compose run $DCA DeMarker30_OpenCondition2
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/DeMarker/Timeframes
    needs: Optimize-OpenCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA DeMarker_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
