---
name: Optimize Strategy AD

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-ad'
      - 'optimize-strategy-ad-*'

jobs:
  CloseCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/AD/CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA AD1_CloseCondition
      - run: docker-compose run $DCA AD5_CloseCondition
      - run: docker-compose run $DCA AD15_CloseCondition
      - run: docker-compose run $DCA AD30_CloseCondition
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  OpenCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/AD/OpenCondition
    needs: CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA AD1_OpenCondition1
      - run: docker-compose run $DCA AD5_OpenCondition1
      - run: docker-compose run $DCA AD15_OpenCondition1
      - run: docker-compose run $DCA AD30_OpenCondition1
      - run: docker-compose run $DCA AD1_OpenCondition2
      - run: docker-compose run $DCA AD5_OpenCondition2
      - run: docker-compose run $DCA AD15_OpenCondition2
      - run: docker-compose run $DCA AD30_OpenCondition2
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/AD/Timeframes
    needs: OpenCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA AD_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
