---
name: Optimize Strategy MFI

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-mfi'
      - 'optimize-strategy-mfi-*'

jobs:
  CloseCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA MFI1_CloseCondition
      - run: docker-compose run $DCA MFI5_CloseCondition
      - run: docker-compose run $DCA MFI15_CloseCondition
      - run: docker-compose run $DCA MFI30_CloseCondition
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  OpenCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/OpenCondition
    needs: CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA MFI1_OpenCondition1
      - run: docker-compose run $DCA MFI5_OpenCondition1
      - run: docker-compose run $DCA MFI15_OpenCondition1
      - run: docker-compose run $DCA MFI30_OpenCondition1
      - run: docker-compose run $DCA MFI1_OpenCondition2
      - run: docker-compose run $DCA MFI5_OpenCondition2
      - run: docker-compose run $DCA MFI15_OpenCondition2
      - run: docker-compose run $DCA MFI30_OpenCondition2
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/Timeframes
    needs: OpenCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA MFI_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git status
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
