---
name: Optimize Strategy CCI

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-cci'
      - 'optimize-strategy-cci-*'

jobs:
  CloseCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/CloseCondition
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
        - CCI1_CloseCondition
        - CCI5_CloseCondition
        - CCI15_CloseCondition
        - CCI30_CloseCondition
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA ${{ matrix.test }}
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  OpenCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/OpenCondition
    needs: CloseCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA CCI1_OpenCondition1
      - run: docker-compose run $DCA CCI5_OpenCondition1
      - run: docker-compose run $DCA CCI15_OpenCondition1
      - run: docker-compose run $DCA CCI30_OpenCondition1
      - run: docker-compose run $DCA CCI1_OpenCondition2
      - run: docker-compose run $DCA CCI5_OpenCondition2
      - run: docker-compose run $DCA CCI15_OpenCondition2
      - run: docker-compose run $DCA CCI30_OpenCondition2
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/Timeframes
    needs: OpenCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA CCI_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
