---
name: Optimize Strategy ADX

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-adx'
      - 'optimize-strategy-adx-*'

jobs:
  CloseCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/ADX/CloseCondition
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - ADX1_CloseCondition
          - ADX5_CloseCondition
          - ADX15_CloseCondition
          - ADX30_CloseCondition
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA ${{ matrix.test }}
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add . && git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  OpenCondition:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/ADX/OpenCondition
    needs: CloseCondition
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - ADX1_OpenCondition1
          - ADX5_OpenCondition1
          - ADX15_OpenCondition1
          - ADX30_OpenCondition1
          - ADX1_OpenCondition2
          - ADX5_OpenCondition2
          - ADX15_OpenCondition2
          - ADX30_OpenCondition2
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA ${{ matrix.test }}
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add . && git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/ADX/Timeframes
    needs: OpenCondition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA ADX_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add . && git add --renormalize .
          git status
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
